version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aeo_audit
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OPENAI_API_KEY=dummy_key
      - ANTHROPIC_API_KEY=dummy_key
    depends_on:
      - db
      - redis
    volumes:
      - ./reports:/app/reports
      - ./alembic:/app/alembic

  worker:
    build: .
    command: celery -A celery_worker --loglevel=info
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aeo_audit
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OPENAI_API_KEY=dummy_key
      - ANTHROPIC_API_KEY=dummy_key
    depends_on:
      - db
      - redis
    volumes:
      - ./reports:/app/reports
      - ./alembic:/app/alembic

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: aeo_audit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
