[tool.black]
line-length = 88
target-version = ['py311']

[tool.ruff]
line-length = 88
select = [
    "F",  # Pyflakes
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "I",  # isort
    "C90", # mccabe complexity
    "N", # pep8-naming
]
ignore = ["N805"]  # Allow first argument names other than 'self' for SQLAlchemy declarative methods

[tool.ruff.per-file-ignores]
"app/db/base_class.py" = ["N805"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
disallow_untyped_defs = true

[tool.bandit]
exclude_dirs = ["tests", "venv", ".venv"]
# Skip some tests that are commonly noisy in our context
skips = [
    "B101",  # assert_used - we use asserts in tests
    "B601",  # paramiko_calls - may be triggered by some libraries
]
# Focus on high and medium severity issues
confidence = "medium"
severity = "medium"
