[tool.black]
line-length = 88
target-version = ['py311']

[tool.ruff]
line-length = 88
select = [
    "F",  # Pyflakes
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "I",  # isort
    "C90", # mccabe complexity
    "N", # pep8-naming
]
ignore = ["N805"]  # Allow first argument names other than 'self' for SQLAlchemy declarative methods

[tool.ruff.per-file-ignores]
"app/db/base_class.py" = ["N805"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
disallow_untyped_defs = true
