"""add report_type and generated_at to report

Revision ID: 26909b33d4d0
Revises: ac553b04ff00
Create Date: 2025-08-26 15:06:00.291800

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26909b33d4d0"
down_revision: Union[str, None] = "ac553b04ff00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("report", sa.Column("report_type", sa.String(), nullable=True))
    op.add_column(
        "report", sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report", "generated_at")
    op.drop_column("report", "report_type")
    # ### end Alembic commands ###
