"""Initial migration

Revision ID: 6ddb5be0e52d
Revises:
Create Date: 2025-07-29 12:39:59.596046

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "6ddb5be0e52d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
