"""Add Question model and update Response model

Revision ID: 81e918a13231
Revises: 91f89eba1cbd
Create Date: 2025-08-05 14:02:13.163824

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81e918a13231"
down_revision: Union[str, None] = "91f89eba1cbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("tokens", sa.JSON(), nullable=True),
        sa.Column("question_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("responses", sa.Column("question_id", sa.String(), nullable=True))
    op.create_foreign_key(None, "responses", "questions", ["question_id"], ["id"])
    op.drop_column("responses", "question")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "responses",
        sa.Column("question", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "responses", type_="foreignkey")
    op.drop_column("responses", "question_id")
    op.drop_table("questions")
    # ### end Alembic commands ###
