"""Add persona model

Revision ID: 85cef3d4fbde
Revises: e9f3577cddaa
Create Date: 2025-10-01 13:58:38.772549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85cef3d4fbde'
down_revision: Union[str, None] = 'e9f3577cddaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auditrun', 'prompt_basket_version')
    op.add_column('job_dependencies', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_job_dependencies_depends_on_id'), 'job_dependencies', ['depends_on_id'], unique=False)
    op.add_column('job_executions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('job_executions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('job_executions_execution_id_key', 'job_executions', type_='unique')
    op.drop_index('ix_job_executions_execution_id', table_name='job_executions')
    op.create_index(op.f('ix_job_executions_execution_id'), 'job_executions', ['execution_id'], unique=True)
    op.drop_index('ix_questions_audit_run_persona', table_name='questions')
    op.drop_index('ix_questions_driver_context_stage', table_name='questions')
    op.drop_column('questions', 'emotional_anchor')
    op.drop_column('questions', 'role')
    op.drop_column('questions', 'seed_type')
    op.drop_column('questions', 'driver')
    op.drop_column('questions', 'persona')
    op.drop_column('questions', 'context_stage')
    op.drop_column('questions', 'provider_version')
    op.drop_column('responses', 'sentiment')
    op.drop_column('responses', 'satisfaction_score')
    op.drop_column('responses', 'satisfaction_model')
    op.drop_column('responses', 'emotional_satisfaction')
    op.add_column('scheduler_locks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('scheduler_locks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scheduler_metrics', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('scheduler_metrics', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler_metrics', 'updated_at')
    op.drop_column('scheduler_metrics', 'created_at')
    op.drop_column('scheduler_locks', 'updated_at')
    op.drop_column('scheduler_locks', 'created_at')
    op.add_column('responses', sa.Column('emotional_satisfaction', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('responses', sa.Column('satisfaction_model', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('responses', sa.Column('satisfaction_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('responses', sa.Column('sentiment', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('provider_version', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('context_stage', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('persona', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('driver', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('seed_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('role', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('emotional_anchor', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_index('ix_questions_driver_context_stage', 'questions', ['driver', 'context_stage'], unique=False)
    op.create_index('ix_questions_audit_run_persona', 'questions', ['audit_run_id', 'persona'], unique=False)
    op.drop_index(op.f('ix_job_executions_execution_id'), table_name='job_executions')
    op.create_index('ix_job_executions_execution_id', 'job_executions', ['execution_id'], unique=False)
    op.create_unique_constraint('job_executions_execution_id_key', 'job_executions', ['execution_id'])
    op.drop_column('job_executions', 'updated_at')
    op.drop_column('job_executions', 'created_at')
    op.drop_index(op.f('ix_job_dependencies_depends_on_id'), table_name='job_dependencies')
    op.drop_column('job_dependencies', 'updated_at')
    op.add_column('auditrun', sa.Column('prompt_basket_version', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
