"""Add Response model and update AuditRun

Revision ID: 8d822df85fc8
Revises: 6ddb5be0e52d
Create Date: 2025-07-31 14:20:25.202008

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "8d822df85fc8"
down_revision: Union[str, None] = "6ddb5be0e52d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "responses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("audit_run_id", sa.UUID(), nullable=True),
        sa.Column("question", sa.String(), nullable=True),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("raw_response", sa.JSON(), nullable=True),
        sa.Column("platform", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["audit_run_id"],
            ["auditrun.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("response")
    op.add_column("auditrun", sa.Column("status", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auditrun", "status")
    op.create_table(
        "response",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("audit_run_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("question_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "raw_response",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["audit_run_id"], ["auditrun.id"], name="response_audit_run_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["question.id"], name="response_question_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="response_pkey"),
    )
    op.drop_table("responses")
    # ### end Alembic commands ###
