"""Add brand_mentions to Response model

Revision ID: b00e2b865774
Revises: 81e918a13231
Create Date: 2025-08-11 17:00:02.250667

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b00e2b865774"
down_revision: Union[str, None] = "81e918a13231"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("responses", sa.Column("brand_mentions", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("responses", "brand_mentions")
    # ### end Alembic commands ###
