"""Add error_log to AuditRun

Revision ID: cfbb21270e7d
Revises: 8d822df85fc8
Create Date: 2025-07-31 14:47:52.234444

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "cfbb21270e7d"
down_revision: Union[str, None] = "8d822df85fc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auditrun", sa.Column("error_log", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auditrun", "error_log")
    # ### end Alembic commands ###
