name: Performance Tests

on:
  workflow_dispatch:

jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest-benchmark

      - name: Run pytest benchmarks
        run: |
          source venv/bin/activate
          pytest -q --benchmark-only --benchmark-min-time=0.01 --benchmark-save=perf

      - name: Upload benchmark data
        uses: actions/upload-artifact@v4
        with:
          name: pytest-benchmark-data
          path: ./.benchmarks
